name: Maria Benton Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94461
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#53322d'
    - '#f48a71'
    - '#e7d3d3'
    - '#000000'
    - '#ff0000'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
